root: true

env:
  es6: true
  node: true

parserOptions:
  ecmaVersion: 8
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
    blockBindings: true

rules:
  no-constant-condition: [1]
  no-inline-comments: [1]
  no-dupe-keys: [1]
  keyword-spacing: [ 1, { before: true, after: true } ]
  no-duplicate-case: [1]
  no-empty: [1]
  semi: [ 0, never ]
  no-sparse-arrays: [1]
  no-unreachable: [1]
  default-case: [1]
  eqeqeq: [1]
  no-caller: [1]
  no-else-return: [1]
  radix: [1]
  indent: [ 1, 2, SwitchCase: 1 ]
  quotes: [ 1, single ]
  linebreak-style: [ 1, unix ]
  no-unused-vars: [1]
  no-use-before-define: [2]
  space-unary-ops: [2]
  no-eval: [2]
  no-extend-native: [2]
  no-proto: [2]
  no-useless-call: [2]
  no-with: [2]
  no-var: [2]
  prefer-const: [2]
  eol-last: [2, always]
  comma-dangle: [1, always-multiline]



