language: node_js

cache:
  directories:
    - "node_modules"

node_js:
  - 10.0.0

notifications:
  email:
    on_success: never

branches:
  only:
    - master

before_install: git fetch --depth=100

install:
  - npm i

script:
  - commitlint-travis
  - npm run lint
  - npm run ci
